### ISSUE TITLE
gyp: Python error

### ISSUE THREAD

**Issue by felloz** [gusjara/Laravel-Vue-Dashboard#1]
I receive this error when run `npm install `

```
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'D:\\isendWell\\vue-dashboard\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.6.2
gyp info using node@12.16.3 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (D:\isendWell\vue-dashboard\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (D:\isendWell\vue-dashboard\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (D:\isendWell\vue-dashboard\node_modules\which\which.js:80:29)
gyp verb `which` failed     at D:\isendWell\vue-dashboard\node_modules\which\which.js:89:16
gyp verb `which` failed     at D:\isendWell\vue-dashboard\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at D:\isendWell\vue-dashboard\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:167:21)
gyp verb `which` failed  python2 Error: not found: python2
gyp verb `which` failed     at getNotFoundError (D:\isendWell\vue-dashboard\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (D:\isendWell\vue-dashboard\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (D:\isendWell\vue-dashboard\node_modules\which\which.js:80:29)
gyp verb `which` failed     at D:\isendWell\vue-dashboard\node_modules\which\which.js:89:16
gyp verb `which` failed     at D:\isendWell\vue-dashboard\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at D:\isendWell\vue-dashboard\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:167:21) {
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\Users\lserrano\AppData\Local\Programs\Python\Python37-32\python.EXE
gyp verb check python version `C:\Users\lserrano\AppData\Local\Programs\Python\Python37-32\python.EXE -c "import platform; print(platform.python_version());"` returned: "3.7.2\r\n"
gyp verb could not find "C:\Users\lserrano\AppData\Local\Programs\Python\Python37-32\python.EXE". checking python launcher
gyp verb could not find "C:\Users\lserrano\AppData\Local\Programs\Python\Python37-32\python.EXE". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:\Users\lserrano\AppData\Local\Programs\Python\Python37-32\python.EXE", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (D:\isendWell\vue-dashboard\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (D:\isendWell\vue-dashboard\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at D:\isendWell\vue-dashboard\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:167:21)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\isendWell\\vue-dashboard\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd D:\isendWell\vue-dashboard\node_modules\node-sass
gyp ERR! node -v v12.16.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1
npm WARN rollback Rolling back source-map@0.4.4 failed (this is probably harmless): EPERM: operation not permitted, lstat 'D:\isendWell\vue-dashboard\node_modules\scss-tokenizer\node_modules'
npm WARN The package vue is included as both a dev and production dependency.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.7.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.7.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\lserrano\AppData\Roaming\npm-cache\_logs\2020-09-15T17_21_45_239Z-debug.log
```

```
λ python --version
Python 3.7.2
```

**Comment by felloz** [comment]
Fixed previus error, i had to downgrade my python version to 2.7 it seems gyp dont work with a higher version.... 

```
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir C:\Users\lserrano\.node-gyp\12.16.3
gyp verb found first Solution file build/binding.sln
gyp verb could not find "msbuild.exe" in PATH - finding location in registry
gyp info spawn C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64'
gyp info spawn args ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Build started 9/15/2020 3:30:22 PM.
Project "D:\isendWell\vue-dashboard\node_modules\node-sass\build\binding.sln" on node 1 (default targets).
ValidateSolutionConfiguration:
  Building solution configuration "Release|x64".
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) in stall Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it is installed elsewhere.  [D:\isendWel l\vue-dashboard\node_modules\node-sass\build\binding.sln]
Done Building Project "D:\isendWell\vue-dashboard\node_modules\node-sass\build\binding.sln" (default targets) -- FAILED.


Build FAILED.

"D:\isendWell\vue-dashboard\node_modules\node-sass\build\binding.sln" (default target) (1) ->
(_src_\libsass target) ->
  MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2)
install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it is installed elsewhere.  [D:\isendW ell\vue-dashboard\node_modules\node-sass\build\binding.sln]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.25
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\isendWell\vue-dashboard\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\isendWell\\vue-dashboard\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd D:\isendWell\vue-dashboard\node_modules\node-sass
gyp ERR! node -v v12.16.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN The package vue is included as both a dev and production dependency.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.7.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.7.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
